name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Sarabun-Thin
      fonts:
        - asset: Sarabun/Sarabun-Thin.ttf
    - family: Sarabun-Light
      fonts:
        - asset: Sarabun/Sarabun-Light.ttf
    - family: Sarabun-Medium
      fonts:
        - asset: Sarabun/Sarabun-Medium.ttf
    - family: Sarabun-Bold
      fonts:
        - asset: Sarabun/Sarabun-Bold.ttf
    - family: Sarabun-ExtraBold
      fonts:
        - asset: Sarabun/Sarabun-ExtraBold.ttf


